# fly.toml app configuration file generated for tunnelicious on 2025-10-17T19:53:21Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tunnelicious'
primary_region = 'jnb'

[build]
  [build.args]
    GO_VERSION = '1.24.1'

[env]
  PORT = '8080'

[http_service]
  internal_port = 22420
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
