name: Build & Release Binaries

on:
  push:
    tags:
      - "v*.*.*" # triggers on tag push

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"

      - name: Build binaries
        run: |
          mkdir -p dist
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} CGO_ENABLED=0 \
          go build -ldflags "-s -w" -o dist/tunnelicious-${{ matrix.goos }}-${{ matrix.goarch }} ./cmd/tunnelicious
          cd dist
          for f in *; do
            zip "$f.zip" "$f"
          done

      - name: Create GitHub Release & Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
